remote_theme: abhinavs/moonwalk
title: Sustentabilidade em Foco
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/sustentabilidade-em-foco"
author: Redação Sustentabilidade em Foco
email: contato@sustentabilidade-em-foco.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
